<?xml version="1.0" encoding="utf-8"?><Database Name="BKMM3" Class="DbMedifirstDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=BKMM3;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BKMM3ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="IdPegawai" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="KdKategoryUser" Type="System.String" DbType="Char(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservasiLogin" Member="ReservasiLogins">
    <Type Name="ReservasiLogin">
      <Column Name="NoCM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoTelp" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StatusEnabled" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="isVerify" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserApiJkn" Member="UserApiJkns">
    <Type Name="UserApiJkn"> 
      <Column Name="userName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>