//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Framework.Helper.ServiceQueue {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Medifirst.Service.Queue")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Core.Framework.Helper.ServiceQueue.Message.TypeMessage TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return AddressField;
            }
            set {
                if ((object.ReferenceEquals(AddressField, value) != true)) {
                    AddressField = value;
                    RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return ContentField;
            }
            set {
                if ((object.ReferenceEquals(ContentField, value) != true)) {
                    ContentField = value;
                    RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return DateField;
            }
            set {
                if ((DateField.Equals(value) != true)) {
                    DateField = value;
                    RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return PortField;
            }
            set {
                if ((PortField.Equals(value) != true)) {
                    PortField = value;
                    RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Core.Framework.Helper.ServiceQueue.Message.TypeMessage Type {
            get {
                return TypeField;
            }
            set {
                if ((TypeField.Equals(value) != true)) {
                    TypeField = value;
                    RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Message.TypeMessage", Namespace="http://schemas.datacontract.org/2004/07/Medifirst.Service.Queue")]
        public enum TypeMessage : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NewPasien = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            UpdatePasien = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CountingPasien = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Other = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AntrianPasienRegistrasi_T", Namespace="http://schemas.datacontract.org/2004/07/Medifirst.Antrian.Domain")]
    [System.SerializableAttribute()]
    public partial class AntrianPasienRegistrasi_T : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KdAntrianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdDokterOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KdHistoryLoginDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KdHistoryLoginIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KdHistoryLoginSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KdHistoryLoginUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdKelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> KdKelompokPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short KdProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KdRuanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeteranganOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NoAntrianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> NoAntrianOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> NoLoketCounterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegistrasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoReturOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> StatusPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TglAntrianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return extensionDataField;
            }
            set {
                extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KdAntrian {
            get {
                return KdAntrianField;
            }
            set {
                if ((KdAntrianField.Equals(value) != true)) {
                    KdAntrianField = value;
                    RaisePropertyChanged("KdAntrian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KdDokterOrder {
            get {
                return KdDokterOrderField;
            }
            set {
                if ((object.ReferenceEquals(KdDokterOrderField, value) != true)) {
                    KdDokterOrderField = value;
                    RaisePropertyChanged("KdDokterOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KdHistoryLoginD {
            get {
                return KdHistoryLoginDField;
            }
            set {
                if ((KdHistoryLoginDField.Equals(value) != true)) {
                    KdHistoryLoginDField = value;
                    RaisePropertyChanged("KdHistoryLoginD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KdHistoryLoginI {
            get {
                return KdHistoryLoginIField;
            }
            set {
                if ((KdHistoryLoginIField.Equals(value) != true)) {
                    KdHistoryLoginIField = value;
                    RaisePropertyChanged("KdHistoryLoginI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KdHistoryLoginS {
            get {
                return KdHistoryLoginSField;
            }
            set {
                if ((KdHistoryLoginSField.Equals(value) != true)) {
                    KdHistoryLoginSField = value;
                    RaisePropertyChanged("KdHistoryLoginS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KdHistoryLoginU {
            get {
                return KdHistoryLoginUField;
            }
            set {
                if ((KdHistoryLoginUField.Equals(value) != true)) {
                    KdHistoryLoginUField = value;
                    RaisePropertyChanged("KdHistoryLoginU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KdKelas {
            get {
                return KdKelasField;
            }
            set {
                if ((object.ReferenceEquals(KdKelasField, value) != true)) {
                    KdKelasField = value;
                    RaisePropertyChanged("KdKelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> KdKelompokPasien {
            get {
                return KdKelompokPasienField;
            }
            set {
                if ((KdKelompokPasienField.Equals(value) != true)) {
                    KdKelompokPasienField = value;
                    RaisePropertyChanged("KdKelompokPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short KdProfile {
            get {
                return KdProfileField;
            }
            set {
                if ((KdProfileField.Equals(value) != true)) {
                    KdProfileField = value;
                    RaisePropertyChanged("KdProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KdRuangan {
            get {
                return KdRuanganField;
            }
            set {
                if ((object.ReferenceEquals(KdRuanganField, value) != true)) {
                    KdRuanganField = value;
                    RaisePropertyChanged("KdRuangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeteranganOrder {
            get {
                return KeteranganOrderField;
            }
            set {
                if ((object.ReferenceEquals(KeteranganOrderField, value) != true)) {
                    KeteranganOrderField = value;
                    RaisePropertyChanged("KeteranganOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short NoAntrian {
            get {
                return NoAntrianField;
            }
            set {
                if ((NoAntrianField.Equals(value) != true)) {
                    NoAntrianField = value;
                    RaisePropertyChanged("NoAntrian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> NoAntrianOrder {
            get {
                return NoAntrianOrderField;
            }
            set {
                if ((NoAntrianOrderField.Equals(value) != true)) {
                    NoAntrianOrderField = value;
                    RaisePropertyChanged("NoAntrianOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCM {
            get {
                return NoCMField;
            }
            set {
                if ((object.ReferenceEquals(NoCMField, value) != true)) {
                    NoCMField = value;
                    RaisePropertyChanged("NoCM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> NoLoketCounter {
            get {
                return NoLoketCounterField;
            }
            set {
                if ((NoLoketCounterField.Equals(value) != true)) {
                    NoLoketCounterField = value;
                    RaisePropertyChanged("NoLoketCounter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegistrasi {
            get {
                return NoRegistrasiField;
            }
            set {
                if ((object.ReferenceEquals(NoRegistrasiField, value) != true)) {
                    NoRegistrasiField = value;
                    RaisePropertyChanged("NoRegistrasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoReturOrder {
            get {
                return NoReturOrderField;
            }
            set {
                if ((object.ReferenceEquals(NoReturOrderField, value) != true)) {
                    NoReturOrderField = value;
                    RaisePropertyChanged("NoReturOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusEnabled {
            get {
                return StatusEnabledField;
            }
            set {
                if ((StatusEnabledField.Equals(value) != true)) {
                    StatusEnabledField = value;
                    RaisePropertyChanged("StatusEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> StatusPasien {
            get {
                return StatusPasienField;
            }
            set {
                if ((StatusPasienField.Equals(value) != true)) {
                    StatusPasienField = value;
                    RaisePropertyChanged("StatusPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TglAntrian {
            get {
                return TglAntrianField;
            }
            set {
                if ((TglAntrianField.Equals(value) != true)) {
                    TglAntrianField = value;
                    RaisePropertyChanged("TglAntrian");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceQueue.IServiceQueue", CallbackContract=typeof(Core.Framework.Helper.ServiceQueue.IServiceQueueCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServiceQueue {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/Subscribe", ReplyAction="http://tempuri.org/IServiceQueue/SubscribeResponse")]
        bool Subscribe(System.Guid guid, Core.Framework.Helper.ServiceQueue.Message.TypeMessage type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/Send", ReplyAction="http://tempuri.org/IServiceQueue/SendResponse")]
        bool Send(Core.Framework.Helper.ServiceQueue.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/UnSubscribe", ReplyAction="http://tempuri.org/IServiceQueue/UnSubscribeResponse")]
        bool UnSubscribe(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/GetListSubscribe", ReplyAction="http://tempuri.org/IServiceQueue/GetListSubscribeResponse")]
        string GetListSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/GetLog", ReplyAction="http://tempuri.org/IServiceQueue/GetLogResponse")]
        string GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQueue/RegistrasiPasien", ReplyAction="http://tempuri.org/IServiceQueue/RegistrasiPasienResponse")]
        Core.Framework.Helper.ServiceQueue.AntrianPasienRegistrasi_T RegistrasiPasien(Core.Framework.Helper.ServiceQueue.AntrianPasienRegistrasi_T antrian);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQueueCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceQueue/ReceiveMessaged")]
        void ReceiveMessaged(Core.Framework.Helper.ServiceQueue.Message message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQueueChannel : Core.Framework.Helper.ServiceQueue.IServiceQueue, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceQueueClient : System.ServiceModel.DuplexClientBase<Core.Framework.Helper.ServiceQueue.IServiceQueue>, Core.Framework.Helper.ServiceQueue.IServiceQueue {
        
        public ServiceQueueClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceQueueClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceQueueClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQueueClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQueueClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Subscribe(System.Guid guid, Core.Framework.Helper.ServiceQueue.Message.TypeMessage type) {
            return base.Channel.Subscribe(guid, type);
        }
        
        public bool Send(Core.Framework.Helper.ServiceQueue.Message message) {
            return base.Channel.Send(message);
        }
        
        public bool UnSubscribe(System.Guid guid) {
            return base.Channel.UnSubscribe(guid);
        }
        
        public string GetListSubscribe() {
            return base.Channel.GetListSubscribe();
        }
        
        public string GetLog() {
            return base.Channel.GetLog();
        }
        
        public Core.Framework.Helper.ServiceQueue.AntrianPasienRegistrasi_T RegistrasiPasien(Core.Framework.Helper.ServiceQueue.AntrianPasienRegistrasi_T antrian) {
            return base.Channel.RegistrasiPasien(antrian);
        }
    }
}
