
/****** Object:  Table [dbo].[ReservasiMobileJKN]    Script Date: 12/28/2021 8:32:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ReservasiMobileJKN](
	[KodeBooking] [char](10) NOT NULL,
 CONSTRAINT [PK_ReservasiMobileJKN] PRIMARY KEY CLUSTERED 
(
	[KodeBooking] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


