//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasamedika.Medifirst.Web.API.ServicesPrinting {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesPrinting.IServices", CallbackContract=typeof(Jasamedika.Medifirst.Web.API.ServicesPrinting.IServicesCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SendMessage", ReplyAction="http://tempuri.org/IServices/SendMessageResponse")]
        void SendMessage(string ip, string value, string Report, bool preview);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Subscribe", ReplyAction="http://tempuri.org/IServices/SubscribeResponse")]
        void Subscribe(string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/RetriveMessage", ReplyAction="http://tempuri.org/IServices/RetriveMessageResponse")]
        void RetriveMessage(string value, string Report, bool preview);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : Jasamedika.Medifirst.Web.API.ServicesPrinting.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.DuplexClientBase<Jasamedika.Medifirst.Web.API.ServicesPrinting.IServices>, Jasamedika.Medifirst.Web.API.ServicesPrinting.IServices {
        
        public ServicesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessage(string ip, string value, string Report, bool preview) {
            base.Channel.SendMessage(ip, value, Report, preview);
        }
        
        public void Subscribe(string ip) {
            base.Channel.Subscribe(ip);
        }
    }
}
