#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiToJKN.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BKMM3")]
	public partial class DbMedifirstDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertReservasiLogin(ReservasiLogin instance);
    partial void UpdateReservasiLogin(ReservasiLogin instance);
    partial void DeleteReservasiLogin(ReservasiLogin instance);
    #endregion
		
		public DbMedifirstDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BKMM3ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbMedifirstDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMedifirstDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMedifirstDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbMedifirstDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<ReservasiLogin> ReservasiLogins
		{
			get
			{
				return this.GetTable<ReservasiLogin>();
			}
		}
		
		public System.Data.Linq.Table<UserApiJkn> UserApiJkns
		{
			get
			{
				return this.GetTable<UserApiJkn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdPegawai;
		
		private System.Data.Linq.Binary _Username;
		
		private System.Data.Linq.Binary _Password;
		
		private char _Status;
		
		private string _KdKategoryUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPegawaiChanging(string value);
    partial void OnIdPegawaiChanged();
    partial void OnUsernameChanging(System.Data.Linq.Binary value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(System.Data.Linq.Binary value);
    partial void OnPasswordChanged();
    partial void OnStatusChanging(char value);
    partial void OnStatusChanged();
    partial void OnKdKategoryUserChanging(string value);
    partial void OnKdKategoryUserChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPegawai", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdPegawai
		{
			get
			{
				return this._IdPegawai;
			}
			set
			{
				if ((this._IdPegawai != value))
				{
					this.OnIdPegawaiChanging(value);
					this.SendPropertyChanging();
					this._IdPegawai = value;
					this.SendPropertyChanged("IdPegawai");
					this.OnIdPegawaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarBinary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarBinary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1) NOT NULL")]
		public char Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KdKategoryUser", DbType="Char(2)")]
		public string KdKategoryUser
		{
			get
			{
				return this._KdKategoryUser;
			}
			set
			{
				if ((this._KdKategoryUser != value))
				{
					this.OnKdKategoryUserChanging(value);
					this.SendPropertyChanging();
					this._KdKategoryUser = value;
					this.SendPropertyChanged("KdKategoryUser");
					this.OnKdKategoryUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReservasiLogin")]
	public partial class ReservasiLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NoCM;
		
		private System.Data.Linq.Binary _Password;
		
		private string _Email;
		
		private string _NoTelp;
		
		private short _StatusEnabled;
		
		private System.Nullable<byte> _isVerify;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoCMChanging(string value);
    partial void OnNoCMChanged();
    partial void OnPasswordChanging(System.Data.Linq.Binary value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNoTelpChanging(string value);
    partial void OnNoTelpChanged();
    partial void OnStatusEnabledChanging(short value);
    partial void OnStatusEnabledChanged();
    partial void OnisVerifyChanging(System.Nullable<byte> value);
    partial void OnisVerifyChanged();
    #endregion
		
		public ReservasiLogin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCM", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NoCM
		{
			get
			{
				return this._NoCM;
			}
			set
			{
				if ((this._NoCM != value))
				{
					this.OnNoCMChanging(value);
					this.SendPropertyChanging();
					this._NoCM = value;
					this.SendPropertyChanged("NoCM");
					this.OnNoCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarBinary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTelp", DbType="VarChar(20)")]
		public string NoTelp
		{
			get
			{
				return this._NoTelp;
			}
			set
			{
				if ((this._NoTelp != value))
				{
					this.OnNoTelpChanging(value);
					this.SendPropertyChanging();
					this._NoTelp = value;
					this.SendPropertyChanged("NoTelp");
					this.OnNoTelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusEnabled", DbType="SmallInt NOT NULL")]
		public short StatusEnabled
		{
			get
			{
				return this._StatusEnabled;
			}
			set
			{
				if ((this._StatusEnabled != value))
				{
					this.OnStatusEnabledChanging(value);
					this.SendPropertyChanging();
					this._StatusEnabled = value;
					this.SendPropertyChanged("StatusEnabled");
					this.OnStatusEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVerify", DbType="TinyInt")]
		public System.Nullable<byte> isVerify
		{
			get
			{
				return this._isVerify;
			}
			set
			{
				if ((this._isVerify != value))
				{
					this.OnisVerifyChanging(value);
					this.SendPropertyChanging();
					this._isVerify = value;
					this.SendPropertyChanged("isVerify");
					this.OnisVerifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserApiJkn")]
	public partial class UserApiJkn
	{
		
		private string _userName;
		
		private string _password;
		
		private System.Nullable<byte> _status;
		
		public UserApiJkn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
